"""Added User Storage Channels for Telegram

Revision ID: 01d6d50de202
Revises: d3cc2b23c3c9
Create Date: 2026-01-25 22:28:49.381180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d6d50de202'
down_revision: Union[str, Sequence[str], None] = 'd3cc2b23c3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_storage_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('file_count', sa.BigInteger(), nullable=False),
    sa.Column('total_size', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_storage_channels_channel_id'), 'user_storage_channels', ['channel_id'], unique=False)
    op.create_index(op.f('ix_user_storage_channels_id'), 'user_storage_channels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_storage_channels_id'), table_name='user_storage_channels')
    op.drop_index(op.f('ix_user_storage_channels_channel_id'), table_name='user_storage_channels')
    op.drop_table('user_storage_channels')
    # ### end Alembic commands ###
