"""added archive schema

Revision ID: 206e8febc210
Revises: 4e0c71086d11
Create Date: 2026-03-07 20:09:45.175335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206e8febc210'
down_revision: Union[str, Sequence[str], None] = '4e0c71086d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('user_folders', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_folders', 'is_archived')
    op.drop_column('user_files', 'is_archived')
    # ### end Alembic commands ###
