"""updated user files  and folders schema

Revision ID: 2b741b4d9683
Revises: cc848fb222bf
Create Date: 2026-02-02 22:22:52.631167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b741b4d9683'
down_revision: Union[str, Sequence[str], None] = 'cc848fb222bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_folders', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_user_folders_folder_name'), table_name='user_folders')
    op.create_index(op.f('ix_user_folders_name'), 'user_folders', ['name'], unique=False)
    op.drop_column('user_folders', 'folder_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_folders', sa.Column('folder_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_folders_name'), table_name='user_folders')
    op.create_index(op.f('ix_user_folders_folder_name'), 'user_folders', ['folder_name'], unique=False)
    op.drop_column('user_folders', 'name')
    # ### end Alembic commands ###
