"""adding folder scehma

Revision ID: 40d342c3f10e
Revises: d421dce70619
Create Date: 2026-01-31 17:23:34.996602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40d342c3f10e'
down_revision: Union[str, Sequence[str], None] = 'd421dce70619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.Column('folder_name', sa.String(length=64), nullable=True),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['user_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_folders_folder_name'), 'user_folders', ['folder_name'], unique=False)
    op.add_column('user_files', sa.Column('parent_folder', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_files', 'user_folders', ['parent_folder'], ['id'])
    op.drop_column('user_files', 'uploaded_at')
    op.drop_column('user_files', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_files', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.drop_column('user_files', 'parent_folder')
    op.drop_index(op.f('ix_user_folders_folder_name'), table_name='user_folders')
    op.drop_table('user_folders')
    # ### end Alembic commands ###
