"""added cascading for user files

Revision ID: 4e0c71086d11
Revises: e10ec11d9448
Create Date: 2026-03-06 23:40:54.171817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0c71086d11'
down_revision: Union[str, Sequence[str], None] = 'e10ec11d9448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_files_parent_id_fkey'), 'user_files', type_='foreignkey')
    op.create_foreign_key(None, 'user_files', 'user_folders', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.create_foreign_key(op.f('user_files_parent_id_fkey'), 'user_files', 'user_folders', ['parent_id'], ['id'])
    # ### end Alembic commands ###
