"""updated userfolder table

Revision ID: 7590aa121060
Revises: 40d342c3f10e
Create Date: 2026-01-31 23:05:51.161953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7590aa121060'
down_revision: Union[str, Sequence[str], None] = '40d342c3f10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_folders_id'), 'user_folders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_folders_id'), table_name='user_folders')
    # ### end Alembic commands ###
