"""add is_deleted to user_folders

Revision ID: 9510deffe07c
Revises: ebeff9d19a9f
Create Date: 2026-02-19 11:36:56.425214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9510deffe07c'
down_revision: Union[str, Sequence[str], None] = 'ebeff9d19a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_folders', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_folders', 'is_deleted')
    # ### end Alembic commands ###
