"""Descriptive message for the migration

Revision ID: bb167e259b54
Revises: 206e8febc210
Create Date: 2026-03-18 17:58:55.652461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb167e259b54'
down_revision: Union[str, Sequence[str], None] = '206e8febc210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_telegram_connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_telegram_connected')
    # ### end Alembic commands ###
