"""updated user files  and folders  schema

Revision ID: cc848fb222bf
Revises: f08f5cdbf223
Create Date: 2026-02-02 21:42:20.754857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc848fb222bf'
down_revision: Union[str, Sequence[str], None] = 'f08f5cdbf223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('user_files_parent_folder_fkey'), 'user_files', type_='foreignkey')
    op.create_foreign_key(None, 'user_files', 'user_folders', ['parent_id'], ['id'])
    op.drop_column('user_files', 'parent_folder')
    op.add_column('user_folders', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('user_folders_parent_folder_id_fkey'), 'user_folders', type_='foreignkey')
    op.create_foreign_key(None, 'user_folders', 'user_folders', ['parent_id'], ['id'])
    op.drop_column('user_folders', 'parent_folder_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_folders', sa.Column('parent_folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_folders', type_='foreignkey')
    op.create_foreign_key(op.f('user_folders_parent_folder_id_fkey'), 'user_folders', 'user_folders', ['parent_folder_id'], ['id'])
    op.drop_column('user_folders', 'parent_id')
    op.add_column('user_files', sa.Column('parent_folder', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.create_foreign_key(op.f('user_files_parent_folder_fkey'), 'user_files', 'user_folders', ['parent_folder'], ['id'])
    op.drop_column('user_files', 'parent_id')
    # ### end Alembic commands ###
