"""Added User Storage Channels for Telegram

Revision ID: d3cc2b23c3c9
Revises: 5acbaa57540a
Create Date: 2026-01-25 20:37:36.511679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cc2b23c3c9'
down_revision: Union[str, Sequence[str], None] = '5acbaa57540a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('telegram_sessions_telegram_user_id_key'), 'telegram_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('telegram_sessions_telegram_user_id_key'), 'telegram_sessions', ['telegram_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('telegram_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
