"""corrected foreign key in user_files

Revision ID: d421dce70619
Revises: 96a9d620b999
Create Date: 2026-01-30 22:21:26.151736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd421dce70619'
down_revision: Union[str, Sequence[str], None] = '96a9d620b999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_files_user_id_key'), 'user_files', type_='unique')
    op.drop_constraint(op.f('user_files_user_id_fkey'), 'user_files', type_='foreignkey')
    op.create_foreign_key(None, 'user_files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.create_foreign_key(op.f('user_files_user_id_fkey'), 'user_files', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('user_files_user_id_key'), 'user_files', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
