"""added cascading for share links

Revision ID: e10ec11d9448
Revises: 17d1f392485a
Create Date: 2026-03-06 23:34:27.614323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10ec11d9448'
down_revision: Union[str, Sequence[str], None] = '17d1f392485a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('share_links_file_id_fkey'), 'share_links', type_='foreignkey')
    op.create_foreign_key(None, 'share_links', 'user_files', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share_links', type_='foreignkey')
    op.create_foreign_key(op.f('share_links_file_id_fkey'), 'share_links', 'user_files', ['file_id'], ['id'])
    # ### end Alembic commands ###
