"""added soft delete schema for files

Revision ID: e8b199c9a214
Revises: ff4219a0a79e
Create Date: 2026-02-21 17:23:44.360853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b199c9a214'
down_revision: Union[str, Sequence[str], None] = 'ff4219a0a79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'is_deleted')
    # ### end Alembic commands ###
