"""add_cascade_delete_to_user_folders_parent_relationship

Revision ID: ebeff9d19a9f
Revises: 26e1a1957e06
Create Date: 2026-02-12 18:02:56.814810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebeff9d19a9f'
down_revision: Union[str, Sequence[str], None] = '26e1a1957e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_folders_parent_id_fkey'), 'user_folders', type_='foreignkey')
    op.create_foreign_key(None, 'user_folders', 'user_folders', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_folders', type_='foreignkey')
    op.create_foreign_key(op.f('user_folders_parent_id_fkey'), 'user_folders', 'user_folders', ['parent_id'], ['id'])
    # ### end Alembic commands ###
