"""updated userfiles  table

Revision ID: f08f5cdbf223
Revises: 7590aa121060
Create Date: 2026-02-01 11:48:07.146533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08f5cdbf223'
down_revision: Union[str, Sequence[str], None] = '7590aa121060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_files', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'updated_at')
    op.drop_column('user_files', 'uploaded_at')
    # ### end Alembic commands ###
