"""added staring for files

Revision ID: ff4219a0a79e
Revises: 9510deffe07c
Create Date: 2026-02-20 22:15:54.370104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4219a0a79e'
down_revision: Union[str, Sequence[str], None] = '9510deffe07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('is_starred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'is_starred')
    # ### end Alembic commands ###
